[package]
name = "radio-sx127x"
description = "Rust driver for the Semtec SX127x Sub GHZ LoRa Radio ICs"
version = "0.10.1"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
repository = "https://github.com/ryankurte/rust-radio-sx127x"
license = "MPL-2.0"
edition = "2018"

[features]
util = [ "structopt", "driver-pal/hal", "simplelog", "humantime" ] 
default = [ "util", "serde" ]

# for examples
stm32f4xx = []
stm32f411 = ["stm32f4xx-hal/stm32f411", "stm32f4xx-hal/rt"] 

[dependencies]
libc = "0.2"
log = { version = "0.4" }
bitflags = "1.0"
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }

structopt = { version = "0.3.21", optional = true }
simplelog = { version = "0.8.0", optional = true }
humantime = { version = "2.0.0", optional = true }
linux-embedded-hal = { version = "0.4.0-alpha.0", optional = true }
driver-cp2130 = { version = "1.0.0-alpha.1", optional = true }

[dependencies.radio]
version = "0.7.0"

[dependencies.embedded-hal]
#version = "1.0.0-alpha.1"
version = "1.0.0-alpha.4"

[dependencies.driver-pal]
version = "0.8.0-alpha.0"
default-features = false

#[dev-dependencies.color-backtrace] # this needs std, which causes example build to fail
#color-backtrace = "0.5"

[dev-dependencies]                     # for examples
cortex-m = "0.6.0"
#nb = "0.1.2"
cortex-m-rt = "0.6.8"
panic-halt = "0.2.0"
panic-semihosting = "0.5.2"
cortex-m-semihosting = "0.3.3"
#embedded-spi  = { version = "0.6", default-features = false }
stm32f4xx-hal = { git = "https://github.com/stm32-rs/stm32f4xx-hal", branch = "master" }
#stm32f4xx-hal = "0.8.3"

[patch."https://github.com/stm32-rs/stm32f4xx-hal"]
stm32f4xx-hal = { git = "https://github.com/maxekman/stm32f4xx-hal", branch="update-to-try-functions" }
#stm32f4xx-hal = { git = "https://github.com/maxekman/stm32f4xx-hal", branch="update-to-try-functions", rev = "https://github.com/stm32-rs/stm32f4xx-hal/commit/dd14acca71a5fcfdfd77bf531a30ab33b7dd2c0a"}

[patch.crates-io]
# Patch for radio-hal to update embedded-hal version
radio = { git = "https://github.com/ryankurte/rust-radio.git", branch = "master" }
#stm32f4xx-hal = { git = "https://github.com/maxekman/stm32f4xx-hal", branch="update-to-try-functions" }
##stm32f4xx-hal = { git = "https://github.com/maxekman/stm32f4xx-hal", branch="update-to-try-functions", rev = "https://github.com/stm32-rs/stm32f4xx-hal/commit/a1316e83dcb1e92fb52cc1d5d04a5bd066f14575"}
##stm32f4xx-hal = { git = "https://github.com/maxekman/stm32f4xx-hal", branch="update-to-try-functions", rev = "https://github.com/stm32-rs/stm32f4xx-hal/commit/dd14acca71a5fcfdfd77bf531a30ab33b7dd2c0a"}


[[bin]]
name = "sx127x-util"
path = "src/util/main.rs"
required-features = ["util"]

[[test]]
name = "integration"
path = "tests/integration.rs"
required-features = ["utils"]



# Fix for libusb-sys package discovery
libusb-sys = { git = "https://github.com/cmsd2/libusb-sys" } 

[[example]]
name = "lora_spi_send"
path = "examples/lora_spi_send.rs"
required-features = ["stm32f4xx", "stm32f411"]
#optional = true

#  build example with (some default-features require std) 
# cargo build   --target thumbv7em-none-eabihf --no-default-features  --features="stm32f411, stm32f4xx"  --example lora_spi_send

